# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790df9c72aa71fa024fa1d1eea8af2a208d0beb7dda124c962e5cd7aca8c79658101089983c9e66ce7da5cd622776e4835408b89111a1f6e00caf9c76abdaf4b

test:
  secret_key_base: f595fa67a7935e7eaf67a3143185d11c56a630f8b2f869837654610cc77bd5ebc68fe58afe28a3dc2cf7dafae06254b4ee06fd6bc147973464a12c033fa05783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
